In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('datacheck_1.csv',parse_dates=['localtime'])
df

userId                   venueId           venueCategoryId  \
0            1  4abc1f51f964a520798620e3  4bf58dd8d48988d1ce941735   
1            1  4d4ac10da0ef54814b6ffff6  4bf58dd8d48988d157941735   
2            1  4db44994cda1c57c82583709  4bf58dd8d48988d1f1931735   
3            1  4a541923f964a52008b31fe3  4bf58dd8d48988d14e941735   
4            1  40f1d480f964a5205b0a1fe3  4bf58dd8d48988d143941735   
...        ...                       ...                       ...   
227423    1083  49f4dca6f964a520626b1fe3  4bf58dd8d48988d1c1941735   
227424    1083  40b68100f964a52085001fe3  4bf58dd8d48988d116941735   
227425    1083  4eda64ced5fb8f213a5d740e  4bf58dd8d48988d176941735   
227426    1083  51140198e4b0874a568cde81  4bf58dd8d48988d162941735   
227427    1083  4a53d9a7f964a520c7b21fe3  4bf58dd8d48988d124941735   

                venueCategory   latitude  longitude                 localtime  \
0          Seafood Restaurant  40.781558 -73.975792 2012-04-04 19:31:31+00:00   
1         American Restaurant  40.784018 -73.974524 2012-04-07 13:42:24+00:00   
2       General Entertainment  40.739398 -73.993210 2012-04-08 14:20:29+00:00   
3         American Restaurant  40.785677 -73.976498 2012-04-08 16:02:10+00:00   
4              Breakfast Spot  40.719929 -74.008532 2012-04-09 12:20:52+00:00   
...                       ...        ...        ...                       ...   
227423     Mexican Restaurant  40.735174 -73.979597 2013-02-01 23:19:34+00:00   
227424                    Bar  40.737831 -73.981022 2013-02-01 23:48:36+00:00   
227425   Gym / Fitness Center  40.746119 -73.993070 2013-02-07 18:37:55+00:00   
227426   Other Great Outdoors  40.757790 -73.981934 2013-02-08 08:15:06+00:00   
227427                 Office  40.745518 -73.992351 2013-02-11 10:49:50+00:00   

        day  daytimelabel  
0         2             6  
1         5             4  
2         6             4  
3         6             5  
4         0             4  
...     ...           ...  
227423    4             7  
227424    4             7  
227425    3             6  
227426    4             2  
227427    0             3  

[227428 rows x 9 columns]

In [5]:
df.localtime[1]

Timestamp('2012-04-07 13:42:24+0000', tz='UTC')

In [7]:
import datetime

In [14]:
u_categories=list(set(df.userId))

In [17]:
min([len(df[df.userId==uid]) for uid in u_categories])

100

In [27]:
df_sub=df[df.userId==uid]
df_sub.sort_values(by=['localtime'],ignore_index=True)

userId                   venueId           venueCategoryId  \
0         2  4ef372169adf60f8399b4bd7  4bf58dd8d48988d16a941735   
1         2  49cbb6f9f964a5200f591fe3  4bf58dd8d48988d1f6941735   
2         2  4b194ddaf964a520efda23e3  4bf58dd8d48988d143941735   
3         2  4beee07fd355a5935b7c0b60  4bf58dd8d48988d110941735   
4         2  4b004fc9f964a520ab3c22e3  4bf58dd8d48988d1f8941735   
..      ...                       ...                       ...   
147       2  4b28e31df964a520ed9524e3  4bf58dd8d48988d172941735   
148       2  4d7e1718e7e1721e5acbd90b  4bf58dd8d48988d1c5941735   
149       2  4b8f50d9f964a520365133e3  4bf58dd8d48988d1fd931735   
150       2  4cc01786ca4aa1cd2cb41db4  4bf58dd8d48988d103941735   
151       2  42ec1480f964a5209e261fe3  4bf58dd8d48988d1e2941735   

              venueCategory   latitude  longitude                 localtime  \
0                    Bakery  40.746577 -73.981732 2012-04-04 09:43:46+00:00   
1          Department Store  40.758315 -73.977284 2012-04-04 11:36:09+00:00   
2            Breakfast Spot  40.624377 -74.148583 2012-04-08 11:11:51+00:00   
3        Italian Restaurant  40.601429 -74.176100 2012-04-09 12:04:38+00:00   
4    Furniture / Home Store  40.652055 -73.870647 2012-04-11 15:43:59+00:00   
..                      ...        ...        ...                       ...   
147             Post Office  40.752830 -73.974959 2013-02-13 09:34:49+00:00   
148          Sandwich Place  40.752443 -73.975046 2013-02-13 10:01:59+00:00   
149                  Subway  40.646099 -73.902669 2013-02-13 13:19:37+00:00   
150          Home (private)  40.562843 -73.918346 2013-02-13 13:45:14+00:00   
151                   Beach  40.567089 -73.865461 2013-02-13 14:16:40+00:00   

     day  daytimelabel  
0      2             3  
1      2             3  
2      6             3  
3      0             4  
4      2             5  
..   ...           ...  
147    2             3  
148    2             3  
149    2             4  
150    2             4  
151    2             4  

[152 rows x 9 columns]

In [74]:
# test
session_dt=datetime.timedelta(hours=72)
S_u={uid:[] for uid in u_categories}
for uid in u_categories:
    df_sub=df[df.userId==uid]
    df_sub.sort_values(by=['localtime'],ignore_index=True,inplace=True)
    for index in df_sub.index:
        if index is 0:  #每个用户最开始时要添加session
            S_u[uid].append([]) #append a session
            r=df_sub[['venueCategory','day','daytimelabel']].iloc[index].to_list()
            S_u[uid][-1].append(r)   #add a record into current session
            continue
        if df_sub.localtime[index]-df.localtime[index-1]>session_dt:    #时间间隔超过72小时添加新session
            S_u[uid].append([]) #append a session
            r=df_sub[['venueCategory','day','daytimelabel']].iloc[index].to_list()
            S_u[uid][-1].append(r)   #add a record into current session
            continue
        # if len(S_u[uid][-1])>=20: #session长度超过20则添加新session
        #     S_u[uid].append([]) #append a session
        #     r=df_sub[['venueCategory','day','daytimelabel']].iloc[index].to_list()
        #     S_u[uid][-1].append(r)   #add a record into current session
        #     continue

        r=df_sub[['venueCategory','day','daytimelabel']].iloc[index].to_list() #普通的连续记录直接添加到当前session
        S_u[uid][-1].append(r)   #add a record into current session

In [75]:
S_u_filtered={uid:[] for uid in u_categories}
for uid in u_categories:
    for session in S_u[uid]:
        if len(session)>=5:
            S_u_filtered[uid].append(session)

In [76]:
len(S_u_filtered)

1083

In [77]:
user_filter=[uid for uid in u_categories if len(S_u_filtered[uid])<5]
for uid in user_filter:
    S_u_filtered.pop(uid)
len(S_u_filtered)

28

In [12]:
import torch
from torch.autograd import Variable

In [2]:
import numpy as np

In [3]:
torch.Tensor([1,2])+np.array([1,2])

tensor([2., 4.], dtype=torch.float64)

In [44]:
x=Variable(torch.Tensor([2]),requires_grad=True)
y=torch.Tensor([10])
z=x*y
z

tensor([20.], grad_fn=<MulBackward0>)

In [45]:
z.backward()

In [46]:
x.grad.data,z.grad,y.grad

(tensor([10.]), None, None)

In [47]:
x.data.add_(-0.1,x.grad.data)
x.grad.data.zero_()

tensor([0.])

In [48]:
z=x*y
z.backward()
z,x.grad

(tensor([10.], grad_fn=<MulBackward0>), tensor([10.]))

In [49]:
x.data.add_(-0.1,x.grad.data)
x.grad.data.zero_()

tensor([0.])